// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.19.6
// source: gogo.proto

package gogo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GreetReq) Reset() {
	*x = GreetReq{}
	mi := &file_gogo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetReq) ProtoMessage() {}

func (x *GreetReq) ProtoReflect() protoreflect.Message {
	mi := &file_gogo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetReq.ProtoReflect.Descriptor instead.
func (*GreetReq) Descriptor() ([]byte, []int) {
	return file_gogo_proto_rawDescGZIP(), []int{0}
}

func (x *GreetReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GreetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeting string `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
}

func (x *GreetRes) Reset() {
	*x = GreetRes{}
	mi := &file_gogo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRes) ProtoMessage() {}

func (x *GreetRes) ProtoReflect() protoreflect.Message {
	mi := &file_gogo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRes.ProtoReflect.Descriptor instead.
func (*GreetRes) Descriptor() ([]byte, []int) {
	return file_gogo_proto_rawDescGZIP(), []int{1}
}

func (x *GreetRes) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

var File_gogo_proto protoreflect.FileDescriptor

var file_gogo_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x08,
	0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x08,
	0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x69, 0x6e, 0x67, 0x32, 0x28, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x1d, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x74, 0x12, 0x09, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x42, 0x27,
	0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x63,
	0x6f, 0x7a, 0x7a, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2f, 0x76, 0x30,
	0x2e, 0x30, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gogo_proto_rawDescOnce sync.Once
	file_gogo_proto_rawDescData = file_gogo_proto_rawDesc
)

func file_gogo_proto_rawDescGZIP() []byte {
	file_gogo_proto_rawDescOnce.Do(func() {
		file_gogo_proto_rawDescData = protoimpl.X.CompressGZIP(file_gogo_proto_rawDescData)
	})
	return file_gogo_proto_rawDescData
}

var file_gogo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gogo_proto_goTypes = []any{
	(*GreetReq)(nil), // 0: GreetReq
	(*GreetRes)(nil), // 1: GreetRes
}
var file_gogo_proto_depIdxs = []int32{
	0, // 0: Greeter.Greet:input_type -> GreetReq
	1, // 1: Greeter.Greet:output_type -> GreetRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gogo_proto_init() }
func file_gogo_proto_init() {
	if File_gogo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gogo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gogo_proto_goTypes,
		DependencyIndexes: file_gogo_proto_depIdxs,
		MessageInfos:      file_gogo_proto_msgTypes,
	}.Build()
	File_gogo_proto = out.File
	file_gogo_proto_rawDesc = nil
	file_gogo_proto_goTypes = nil
	file_gogo_proto_depIdxs = nil
}
